#! /bin/bash

# Copyright 2019 Alejandro de Tovar
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files 
# (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, 
# publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR 
# ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

HTTP_DIR="/etc/httpd"
HTTP_DIR_ENABLED="$HTTP_DIR/sites-enabled"

FILE=

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

while [ $# -gt 0 ] ; do
  case $1 in
    *) FILE=$1 ;;
  esac
  shift
done

VHOST="$HTTP_DIR_ENABLED/$FILE"

_remove_link() {
    unlink "$VHOST"
    
    if [ -f $VHOST ]; then
        echo "Falied to remove sym link in $VHOST"
        exit 2
    else
        echo "Vhost sucessfully removed"
        echo "Please reload the apache server \"systemctl restart httpd\""
    fi
}

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

if [ -z "$FILE" ]; then 
    echo "No virtual host passed"
    exit 2
fi

if [ -f $VHOST ]; then
    _remove_link
else 
    echo "Site \"$VHOST\" not exist; Please select a valid one"
    exit 2
fi

exit 0