#! /bin/bash

HTTP_DIR="/etc/httpd"
HTTP_DIR_ENABLED="$HTTP_DIR/sites-enabled"

FILE=

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

while [ $# -gt 0 ] ; do
  case $1 in
    *) FILE=$1 ;;
  esac
  shift
done

VHOST="$HTTP_DIR_ENABLED/$FILE"

_remove_link() {
    unlink "$VHOST"
    
    if [ -f $VHOST ]; then
        echo "Falied to remove sym link in $VHOST"
        exit 2
    else
        echo "Vhost sucessfully removed"
        echo "Please reload the apache server \"systemctl restart httpd\""
    fi
}

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

if [ -z "$FILE" ]; then 
    echo "No virtual host passed"
    exit 2
fi

if [ -f $VHOST ]; then
    _remove_link
else 
    echo "Site \"$VHOST\" not exist; Please select a valid one"
    exit 2
fi

exit 0